node_js:
   - "0.10"
  # - "0.8"
   #- "0.11"

# exclude
#branches:
 # except:
  #  - master
language: node_js
addons:
  firefox: "21.0"
  hosts: 
    - google.com
    - asdf.com
  

  
before_script: mkdir -p shippable/codecoverage
after_script: 
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u tdd 
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
matrix:
 include: 
  - node_js: 0.11
after_success :
  - git push git@heroku.com:testingci.git master
